name: Scala CI Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  compile:
    needs: lint
    uses: ./.github/workflows/compile.yml

  test:
    needs: compile
    uses: ./.github/workflows/test.yml
